### PR TITLE
Remove glpk warnings and strengthen mccs code

### PR DESCRIPTION
**Pull request by MisterDA**

### CODE REVIEW

**Comment by rjbou** [comment]
Thanks for the PR! Can you separate into 2 PRs, one for whitespaces, another fro compilation fixes ?

**Comment by MisterDA** [comment]
> Thanks for the PR! Can you separate into 2 PRs, one for whitespaces, and another for compilation fixes?

Done, whitespace removal is now #46.

**Comment by MisterDA** [comment]
Some of the warnings raised will be fixed in an upcoming version of glpk.

**Review by kit-ty-kate — APPROVED** [review]
Instead of trying to detect the current C compiler i changed the code to simply disable every warnings in glpk as it's not section of the code we (should) change given it is a simple vendor. The previous version with `-Wall` would show a wall off warnings that we wouldn't be able to fix.

LGTM now

**Comment by kit-ty-kate** [comment]
Thanks!

**Pull request merged**
