### PR TITLE
Update to GLPK 4.65

### PR DESCRIPTION
**Pull request by MisterDA**
GLPK 4.65 was released on Thu Feb 16 10:00:00 2018, and is present in Debian Buster (stable).

### CODE REVIEW

**Comment by dra27** [comment]
Is the second commit (changing the sources) strictly required? When vendoring, it's better to keep the patches only to the ones which _must_ happen.

**Comment by dra27** [comment]
GLPK 5.0 was released in December, so we should try to do that as well

**Comment by MisterDA** [comment]
I don't remember... I was irritated by the CI failing and it appeared it didn't really need the glpk update for what I was working on at the time. Updating GLPK seems the best option.

**Comment by AltGr** [comment]
Thanks a lot! I just integrated this (manually) into master ; On a test case I get more than x2 steedup on opam resolution !

**Pull request closed without merging**
